# Generated by Django 6.1.1 on 2026-09-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['added_at']},
        ),
    ]
