# Generated by Django 6.1.1 on 2026-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectmember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='specialty',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend developer'), ('backend', 'Backend developer'), ('debugger', 'Debugger'), ('designer', 'Designer')], max_length=20),
        ),
    ]
