# Generated by Django 6.1.1 on 2026-09-14 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0003_issue_milestone'),
        ('projects', '0003_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(unique=True)),
                ('github_username', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepositoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('webhook_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_github_repos', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_link', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_pr_id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('merged', models.BooleanField(default=False)),
                ('author_username', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('head_ref', models.CharField(blank=True, max_length=255)),
                ('base_ref', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issues', models.ManyToManyField(blank=True, related_name='linked_pull_requests', to='issues.issue')),
                ('repo_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='integrations.githubrepositorylink')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('repo_link', 'github_pr_id')},
            },
        ),
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('author_username', models.CharField(blank=True, max_length=255)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issues', models.ManyToManyField(blank=True, related_name='linked_commits', to='issues.issue')),
                ('repo_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='integrations.githubrepositorylink')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repo_link', 'sha')},
            },
        ),
    ]
