# Generated by Django 6.1.1 on 2026-09-14 10:48

import apps.integrations.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubaccount',
            name='access_token',
            field=apps.integrations.fields.EncryptedCharField(max_length=500),
        ),
    ]
