# Generated by Django 6.1.1 on 2026-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_githubaccount_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubcommit',
            name='branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='committed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubrepositorylink',
            name='default_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='githubrepositorylink',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubrepositorylink',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
