# Generated by Django 6.1.1 on 2026-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='github_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
