# Generated by Django 6.1.1 on 2026-09-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['joined_at']},
        ),
    ]
