# Generated by Django 6.1.1 on 2026-09-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'ordering': ['joined_at']},
        ),
    ]
