# Generated by Django 6.1.1 on 2026-09-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramAccount',
        ),
    ]
